Unattended Running
brianlala/AutoSPSourceBuilder pull request #68
Opened 2020-05-30 15:39 UTC by shurick81

#40

2020-06-02 14:40 UTC, shurick81 commented
@brianlala let me know if you think I need to improve anything more

2020-06-09 12:50 UTC, shurick81 commented
By the way I have now tested it with CI run in GitLab and it worked just fine with my changes

2020-06-23 14:14 UTC, shurick81 commented
hi @brianlala was I too late before summer time :)

2021-08-16 15:56 UTC, shurick81 commented
@brianlala, would you like to merge this in order to make this script possible to run unattended?

2021-08-17 00:07 UTC, brianlala requested changes
Looks good, and sorry for the delay in reviewing! Just see inline commands and watch for style.

2021-08-17 00:07 UTC, brianlala commented on Scripts/AutoSPSourceBuilder.ps1
> +.PARAMETER Unattend
Could you please update the parameter name to "Unattended"?

2021-08-17 00:07 UTC, brianlala commented on Scripts/AutoSPSourceBuilder.ps1
> +    Disables additional user interation so that command can be run in CI/CD pipelines
Minor changes, "interation" should be **interaction** and replace "command" with "script"

2021-08-17 00:07 UTC, brianlala commented on Scripts/AutoSPSourceBuilder.ps1
> +    if ( !$Unattend ) {
Could you please follow the style convention here and elsewhere (open brace on new line, watch out for extra/trailing spaces, etc.)?

2021-12-09 15:33 UTC, shurick81 commented
Thanks Brian, now everything looks good

2021-12-09 20:52 UTC, brianlala approved these changes

2021-12-09 20:54 UTC, merged